### ISSUE TITLE
React native jitsi Android app crashes 

### ISSUE THREAD

**Issue by dpkpanchal38-web** [skrafft/react-native-jitsi-meet#100]
2020-01-29 15:03:47.102 26106-26106/com.inetwork1 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.inetwork1, PID: 26106
    java.lang.AssertionError: Activity needs to be set if initial lifecycle state is resumed
        at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:35)
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:239)
        at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:158)
        at org.jitsi.meet.sdk.BaseReactView.<init>(BaseReactView.java:104)
        at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:102)
        at com.reactnativejitsimeet.JitsiMeetNavigatorActivity.onCreate(JitsiMeetNavigatorActivity.java:56)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

version 
"react": "16.6.3",
"react-native": "^0.59.2",
"react-native-jitsi-meet": "^1.2.0",

**Comment by hasgardee** [comment]
@dpkpanchal38-web did you fixed it?

**Comment by dpkpanchal38-web** [comment]
Yes, I fixed this by calling Java code into react-native

**Comment by dpkpanchal38-web** [comment]
@hasgardee Yes, I fixed this by calling Java code into react-native

**Comment by hasgardee** [comment]
@dpkpanchal38-web could you please explain?

**Comment by dpkpanchal38-web** [comment]
@hasgardee I'm implemented using native code 
First I've use the android native code into android folder and access that code using package into react native file and pass url from react-native file to android native file.
You can google it "how to access android native code into react-native" you will get lot of examples.

**Comment by hasgardee** [comment]
ok.. thanks. actually my issue was a conflict with `react-native-codepush`. so set bundle name to app.bundle and it solves my issue.

**Comment by jbg** [comment]
Since this issue has seen no activity for several months, and seems to already be solved, I'm closing it as part of triaging all open issues. If I made a mistake, please re-open with a comment summarising the current state of the issue.
