### ISSUE TITLE
Error using custom SDK on Android

### ISSUE THREAD

**Issue by SeveHo** [skrafft/react-native-jitsi-meet#106]
Hey, I tried using my own SDK for Android because of UI adjustments. The current setup looks like this:

**android/build.gradle**
```gradle
...
allprojects {
    repositories {
       ...
        maven { url "file:../../frameworks/android/jitsi" }
       ...
        }
    }
...
```

**android/app/build.gradle**
```gradle
...
project.ext.react = [
    entryFile: "index.js",
    bundleAssetName: "app.bundle",
    enableHermes: false,
]
...
def enableHermes = project.ext.react.get("enableHermes", false);
...
dependencies {
    ...
    implementation(project(':react-native-jitsi-meet')) {
        exclude group: 'com.facebook.react',module:'react-native-vector-icons'
        exclude group: 'com.facebook.react',module:'react-native-fast-image'
        exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
        exclude group: 'com.facebook.react',module:'react-native-webview'
        exclude group: 'com.facebook.react',module:'react-native-community_netinfo'
    }

    implementation ('org.jitsi.react:jitsi-meet-sdk:2.6.0') {
      transitive = true
    }
    ...
}
```

With Hermes **diabled** because mobx v5 is incompatible with Hermes. The build works fine and my application runs but when I enter a Jitsi session the app crashes with this error:
```
JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
JitsiMeetSDK: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
JitsiMeetSDK:  at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
JitsiMeetSDK:  at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
JitsiMeetSDK:  at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
JitsiMeetSDK:  at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
JitsiMeetSDK:  at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
JitsiMeetSDK:  at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
JitsiMeetSDK:  at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
JitsiMeetSDK:  at java.lang.Thread.run(Thread.java:764)

```

I'm a bit clueless because of this right now. I thought upgrading the sdk from 2.4.0 to 2.6.0 would help like discussed here: https://github.com/jitsi/jitsi-meet/issues/4971.

Did anyone made similar experiences and was able to solve this problem? Or am I doing something wrong the way I override the SDK used by this package?

I build the SDK following the tutorial from Jitsi: [Build and use your own SDK artifacts/binaries](https://github.com/jitsi/jitsi-meet/tree/master/android#build-and-use-your-own-sdk-artifactsbinaries)

**Versions:**
RN: 61.5
Jitsi SDK: 2.6.0 Tag https://github.com/jitsi/jitsi-meet/releases/tag/android-sdk-2.6.0
ract-native-jitsi-meet: 2.1.1

**Comment by LeoMosiah** [comment]
Enable hermes on yout project and exclude hermes inside ```implementation(project(':react-native-jitsi-meet'))```. It should fix it.

**Comment by zhenghow93** [comment]
Hi @SeveHo , did you manage to solve it without enabling hermes?

**Comment by SeveHo** [comment]
No unfortunately not. It works fine with Hermes but I'd love to se a solution without being forced to use it.

**Comment by SeveHo** [comment]
Addition to @LeoMosiah comment: For my setup the dependencies section in `android/app/build.gradle` looks like this now: 

```gradle
dependencies {
   ...
    implementation(project(':react-native-jitsi-meet')) {
      exclude group: 'com.facebook',module:'hermes'
      exclude group: 'com.facebook.react',module:'react-native-vector-icons'
      exclude group: 'com.facebook.react',module:'react-native-fast-image'
      exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
      exclude group: 'com.facebook.react',module:'react-native-webview'
      exclude group: 'com.facebook.react',module:'react-native-community_netinfo'
      exclude group: 'com.facebook.react',module:'react-native-linear-gradient'
      exclude group: 'com.facebook.react',module:'react-native-svg'
    }

    implementation ('org.jitsi.react:jitsi-meet-sdk:2.6.0') {
      exclude group: 'com.facebook',module:'hermes'
      exclude group: 'com.facebook.react',module:'react-native-vector-icons'
      exclude group: 'com.facebook.react',module:'react-native-fast-image'
      exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
      exclude group: 'com.facebook.react',module:'react-native-webview'
      exclude group: 'com.facebook.react',module:'react-native-community_netinfo'
      exclude group: 'com.facebook.react',module:'react-native-linear-gradient'
      exclude group: 'com.facebook.react',module:'react-native-svg'
      transitive = true
    }
   ...
}
```

**Comment by alexandrtovmach** [comment]
This issue marked as staled!
It'll be closed in 10 days, if there will be no activity. Please let us know if this issue still not resolved and/or bug still reproducing in the latest version.
