### ISSUE TITLE
Android: React Native version mismatch

### ISSUE THREAD

**Issue by sulagarde** [skrafft/react-native-jitsi-meet#116]
Hi,
I follow readme instruction but when I run my app with Android I have this error :
```javascript
React Native version mismatch.
Javascript version 0.60.6
Native version 0.61.5
```
React Native : 0.60.6
react-native-jitsi-meet: 2.1.1

I clear project and build, restart android studio but the error still there.

**Comment by skrafft** [comment]
Hi @sulagarde,

Jitsi Meet has been compiled with RN 0.60.6 and you are using RN 0.61.5, sadly, you need to downgrade to RN 0.60.6 for this to work, there's currently no other way.

**Comment by sulagarde** [comment]
Hi @skrafft I am using RN 0.60.6. I check Jitsi meet dependencies and it look likes it force use rn 0.61.+

````
+--- project :react-native-jitsi-meet
|    \--- org.jitsi.react:jitsi-meet-sdk:2.4.0
|         +--- com.facebook.react:react-native:0.61.1 -> 0.61.5 (*)
```

**Comment by skrafft** [comment]
@sulagarde My bad, I misread the first message. So you have to upgrade to RN 0.61.* to be compatible with jitsi meet version.

**Comment by sulagarde** [comment]
Is there an other solution? I have more packages than this one. I didt the update on friday and after that I had a crash on Android on start call (something about argument missing, expected 3 received 2, I don't remember exactly what was the function) and I got this bug on iOs => [issue 85](https://github.com/skrafft/react-native-jitsi-meet/issues/85).

Maybe you could add this compatibility information to the README?

**Comment by sulagarde** [comment]
Also it works perfectly on iOs with rn 0.60.6 so I think it's something with gradle and dependencies resolution

**Comment by skrafft** [comment]
maybe you can try forcing RN 0.60.6 everywhere (package.json):

```
npm install react-native@0.60.6
```
 and in you build.gradle:
```
implementation ("com.facebook.react:react-native:0.60.6")  { force = true }
```

Not really sure if it will work. @jean-ben-guigui, I've read in #85 that you are using RN 0.60.6, do you have any insights on how to make it work with version 2.1.1 of react-native-jitsi-meet ?

**Comment by sulagarde** [comment]
I also tried 
```
implementation ("com.facebook.react:react-native:0.60.6")  { force = true }
```
I encountered this issue https://github.com/jitsi/jitsi-meet/issues/4689. 😅

**Comment by jean-ben-guigui** [comment]
What I would do is use a SDK of jitsi-meet with a version 0.60.+
You can specify in your dependencies the jitsi-meet-maven-repository you want to use, take a look at the following issue #57

**Comment by nvme978** [comment]
@jean-ben-guigui Thanks for the tip above. I'm on RN v0.60.3 and have managed to fork the maven repo to the commit I want. Now `react-native run-android` fails with error 

```> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find org.jitsi.react:jitsi-meet-sdk:2.4.0.
     Required by:
         project :app > project :react-native-jitsi-meet

**Comment by baotoan1905** [comment]
@sulagarde Was you able to fix this issue. I got same issue in react-native 0.61.5 and jitsi-meet sdk 2.4.0 
`E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    com.facebook.react.bridge.NativeArgumentsParseException: RNCNetInfo.getCurrentState got 2 arguments, expected 3
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:348)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
`

**Comment by sulagarde** [comment]
@baotoan1905 No I did not so for android I redirect to jisti app 🤷‍♀️

**Comment by baotoan1905** [comment]
> @baotoan1905 No I did not so for android I redirect to jisti app 🤷‍♀️

@sulagarde 
Finally I fixed this issue,
By upgrading gradle to 3.5.2 classpath 'com.android.tools.build:gradle:3.5.2' and downgrade @react-native-community/netinfo to 5.0.0.
Hope it can help you.

**Comment by sivakavipondybiz** [comment]
@baotoan1905 
I tried with your suggestion but got same error

dependencies {
        classpath("com.android.tools.build:gradle:3.5.2")
        classpath 'com.google.gms:google-services:4.3.3'  
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

"@react-native-community/netinfo": "^5.0.0",

**Comment by alexandrtovmach** [comment]
This issue marked as staled!
It'll be closed in 10 days, if there will be no activity. Please let us know if this issue still not resolved and/or bug still reproducing in the latest version.
