### ISSUE TITLE
com.facebook.react.common.JavascriptException

### ISSUE THREAD

**Issue by mark-slepkov** [skrafft/react-native-jitsi-meet#121]
Hi everyone. Can you please help me out guys?
What can be reason of this error right after ```JitsiMeet.call(url, userInfo);```?
```com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't.languages')```

I did all the steps described in Readme.md
My react-native info:
```
System:
    OS: Linux 5.3 Linux Mint 19.3 (Tricia)
    CPU: (4) x64 Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
    Memory: 142.88 MB / 11.62 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    npm: 6.10.3 - /usr/local/bin/npm
  npmPackages:
    react: 16.8.1 => 16.8.1 
    react-native: ^0.61.2 => 0.61.2
```

**Comment by mark-slepkov** [comment]
Here is the full listing of the error:

```
2020-04-01 15:13:29.917 11101-11224/com.rhos E/ReactNativeJS: TypeError: null is not an object (evaluating 't.languages')
2020-04-01 15:13:29.923 11101-11224/com.rhos E/ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
    
    --------- beginning of crash
2020-04-01 15:13:29.940 11101-11225/com.rhos E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.rhos, PID: 11101
    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't.languages'), stack:
    <unknown>@1149:191
    v@2:1474
    <unknown>@1148:118
    v@2:1474
    <unknown>@380:275
    v@2:1474
    <unknown>@6:58
    v@2:1474
    d@2:876
    global code@2624:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:176)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
2020-04-01 15:13:29.961 11101-11225/com.rhos E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't.languages'), stack:
    <unknown>@1149:191
    v@2:1474
    <unknown>@1148:118
    v@2:1474
    <unknown>@380:275
    v@2:1474
    <unknown>@6:58
    v@2:1474
    d@2:876
    global code@2624:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:176)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
    
    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't.languages'), stack:
    <unknown>@1149:191
    v@2:1474
    <unknown>@1148:118
    v@2:1474
    <unknown>@380:275
    v@2:1474
    <unknown>@6:58
    v@2:1474
    d@2:876
    global code@2624:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:176)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)

```

Thank you in advance!

**Comment by lironsher** [comment]
Is it only in Release build ?

**Comment by hasgardee** [comment]
@lironsher yeah..facing same issue.. any fix? @mark-slepkov

**Comment by hasgardee** [comment]
Finally fixed it. `react-native-codepush` was causing issues for me. try disabling it. codepush bundle name is different than app.bundle I guess. So, want to make both same to run codepush and react-native-jitsi-meet

**Comment by focalsolution** [comment]
I also face this same problem but on Debug build. I do not use 'react-native-codepush'
Do you have any suggestions?

**Comment by bayazetyan** [comment]
@focalsolution check your bundle name , you need change `index.android.bundle` to `app.bundle` (or other name) 

```java
// android/app/build.gradle
project.ext.react = [
    entryFile: "index.js",
    bundleAssetName: "app.bundle",
]
```

do not forget remove old `index.android.bundle` file in android/app/src/main/assets

**Comment by focalsolution** [comment]
@bayazetyan Thank you for your help.
After removing index.adnroid.bundle and us app.bundle instead, I do not see this Exception anymore.
