### ISSUE TITLE
Crashes app on Android

### ISSUE THREAD

**Issue by Evanfeenstra** [skrafft/react-native-jitsi-meet#123]
Hi! Really hoping to get this package workin in our app. Here is the codebase: https://github.com/stakwork/sphinx-android

When I run "JitsiMeet.call", the app simply crashes. I have tried many different combinations of the setup instruction in the readme. The app is android-only btw (not using expo)

Using logcat gives these errors on the crash:
```
TypeError: null is not an object (evaluating 't(r(d[1])).default.Direction')
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
ReactInstanceManager.detachViewFromInstance()
```

**Comment by lironsher** [comment]
Interesting, I have a similar issue with different error msg: 
`JavascriptException: TypeError: Cannot read property 'Direction' of null, js engine: hermes`

did you any lead?

**Comment by Evanfeenstra** [comment]
I pretty sure the "Direction" thing is coming from react-native-gesture-handler .. but I haven't figured out how to fix yet

**Comment by lironsher** [comment]
I managed to solve that by recompiling jitsi meet sdk, but once it solve, I get more and more issues.

**Comment by antoinefotso** [comment]
any update about this ? my app still stop after while joining conference

**Comment by cristinaalexandru21** [comment]
Did any of you managed to solve the issue? I''m having the same problem.

**Comment by filipef101** [comment]
Same here

**Comment by filipef101** [comment]
Only on release

**Comment by filipef101** [comment]
<details>
<summary>Details</summary>

```
  --------- beginning of crash
2020-04-14 11:52:26.526 28930-29353/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.logirix.sippy.test, PID: 28930
    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't(r(d[1])).default.Direction'), stack:
    <unknown>@392.js:1:133
    v@2:1474
    <unknown>@384.js:1:685
    v@2:1474
    <unknown>@11.js:1:241
    v@2:1474
    <unknown>@10.js:1:313
    v@2:1474
    <unknown>@1.js:1:54
    v@2:1474
    d@2:876
    global code@7:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
2020-04-14 11:52:26.527 28930-29353/? E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't(r(d[1])).default.Direction'), stack:
    <unknown>@392.js:1:133
    v@2:1474
    <unknown>@384.js:1:685
    v@2:1474
    <unknown>@11.js:1:241
    v@2:1474
    <unknown>@10.js:1:313
    v@2:1474
    <unknown>@1.js:1:54
    v@2:1474
    d@2:876
    global code@7:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
    
    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't(r(d[1])).default.Direction'), stack:
    <unknown>@392.js:1:133
    v@2:1474
    <unknown>@384.js:1:685
    v@2:1474
    <unknown>@11.js:1:241
    v@2:1474
    <unknown>@10.js:1:313
    v@2:1474
    <unknown>@1.js:1:54
    v@2:1474
    d@2:876
    global code@7:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
```
</details>

**Comment by adamthewan** [comment]
I am experiencing the same error with no luck solving this

**Comment by adamthewan** [comment]
Guys, I used Solution 2 that this guy mentioned, and it solved my issue:
https://github.com/skrafft/react-native-jitsi-meet/issues/117#issuecomment-636263779

**Comment by devcosta** [comment]
Same problem here

**Comment by hasgardee** [comment]
Finally fixed it. `react-native-codepush` was causing issues for me. try disabling it. codepush bundle name is different than app.bundle I guess. So, want to make both same to run codepush and react-native-jitsi-meet

**Comment by alexandrtovmach** [comment]
This issue marked as staled!
It'll be closed in 10 days, if there will be no activity. Please let us know if this issue still not resolved and/or bug still reproducing in the latest version.
