### ISSUE TITLE
Could not find org.jitsi.react:jitsi-meet-sdk:2.4.0.

### ISSUE THREAD

**Issue by shareef-dweikat** [skrafft/react-native-jitsi-meet#148]
I get This error when i run npx react-native run-android
OS: Windows 10
___

BUILD FAILED in 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find org.jitsi.react:jitsi-meet-sdk:2.4.0.
     Searched in the following locations:
       - file:/C:/Users/Shareef/.m2/repository/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom
       - file:/C:/Users/Shareef/Documents/react-native/react-native/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom
       - file:/C:/Users/Shareef/Documents/react-native/react-native/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom
       - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom
       - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom
       - https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/2.4.0/jitsi-meet-sdk-2.4.0.pom
     Required by:
         project :app > project :react-native-jitsi-meet

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get     Required by:
         project :app > project :react-native-jitsi-meet

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

    at makeError (C:\Users\Shareef\Documents\react-native\react-native\node_modules\execa\index.js:174:9)
    at C:\Users\Shareef\Documents\react-native\react-native\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (C:\Users\Shareef\Documents\react-native\react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\Shareef\Documents\react-native\react-native\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)

**Comment by lamualfa** [comment]
Please attach `android/build.gradle` and `android/app/build.gradle` files.
