### ISSUE TITLE
App crashes when I launch Jitsi meet in release app. Working fine in development environment

### ISSUE THREAD

**Issue by jogidipen** [skrafft/react-native-jitsi-meet#149]
App crashes when I launch Jitsi meet in release app. Working fine in development environment

    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't(r(d[1])).default.Direction'), stack:
    <unknown>@484:133
    v@2:1474
    <unknown>@476:810
    v@2:1474
    <unknown>@475:241
    v@2:1474
    <unknown>@474:313
    v@2:1474
    <unknown>@470:280
    v@2:1474
    <unknown>@469:190
    v@2:1474
    <unknown>@462:2805
    v@2:1474
    <unknown>@386:238
    v@2:1474
    <unknown>@6:58
    v@2:1474
    d@2:876
    global code@720:4
com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
2020-05-01 23:47:12.808 6413-6629/? E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't(r(d[1])).default.Direction'), stack:

Please help me with this issue.

**Comment by jogidipen** [comment]
I did not follow "Android Manual Install" steps. which was already mentioned. I forgot that because it was working fine without doing those steps on while debugging.

**Comment by AdemOch** [comment]
> I did not follow "Android Manual Install" steps. which was already mentioned. I forgot that because it was working fine without doing those steps on while debugging.

@jogidipen so do you mean that we have to apply manual installation as well ??

**Comment by jogidipen** [comment]
for me that was that case. It was working fine with development version. but for release it was crashing. I thought of giving a try it manual steps if it works. and it started working for me. @AdemOch

**Comment by AdemOch** [comment]
> for me that was that case. It was working fine with development version. but for release it was crashing. I thought of giving a try it manual steps if it works. and it started working for me. @AdemOch


what configuration do you have I mean RN and react-native-jitsi-meet? 
also ]did you have any problems while building the release because for me that's the problem 
thank you

**Comment by jogidipen** [comment]
https://www.npmjs.com/package/react-native-jitsi-meet#android-manual-install
I applied this changes.

**Comment by paulignupplabs** [comment]
Any updates here?

**Comment by hemant2capgemini** [comment]
I am also facing an issue with the Release build. any updates?
