### ISSUE TITLE
IOS 13 App get crash in case of video call 

### ISSUE THREAD

**Issue by ninjacoderrakesh** [skrafft/react-native-jitsi-meet#151]
I have added react-native-jitsi-meet in my project. it's getting crash when we start video call in ios 13 except this working fine. this is the crash log for ios 13. 

2020-05-06 16:46:52.953583+0530 RockOutLoudS[492:58405] *** Assertion failure in -[FBSSerialQueue assertOnQueue], /BuildRoot/Library/Caches/com.apple.xbs/Sources/FrontBoardServices/FrontBoard-626.4.1/FrontBoardServices/FBSSerialQueue.m:98
2020-05-06 16:47:05.538217+0530 RockOutLoudS[492:58405] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'threading violation: expected the main thread'

**Comment by fahadhaq** [comment]
Did you manage to find a fix for this? Thanks in advance

**Comment by vickyramz** [comment]
java.lang.SecurityException: PhoneAccount connection service requires BIND_TELECOM_CONNECTION_SERVICE permission.
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at com.android.internal.telecom.ITelecomService$Stub$Proxy.registerPhoneAccount(ITelecomService.java:1048)
	at android.telecom.TelecomManager.registerPhoneAccount(TelecomManager.java:1000)
	at org.jitsi.meet.sdk.ConnectionService.registerPhoneAccount(ConnectionService.java:328)
	at org.jitsi.meet.sdk.RNConnectionService.startCall(RNConnectionService.java:88)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
	at android.os.Looper.loop(Looper.java:201)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.telecom.PhoneAccountRegistrar.registerPhoneAccount(PhoneAccountRegistrar.java:678)
	at com.android.server.telecom.TelecomServiceImpl$1.registerPhoneAccount(TelecomServiceImpl.java:455)
	at com.android.internal.telecom.ITelecomService$Stub.onTransact(ITelecomService.java:237)
	at android.os.Binder.execTransact(Binder.java:726)
