### ISSUE TITLE
Expo 39 Bare Workflow Release crash

### ISSUE THREAD

**Issue by localhosted** [skrafft/react-native-jitsi-meet#222]
I followed the Android Install section in the readme, but when running the release it crashes immediatly:

```
0-08 19:54:04.442  2809  2832 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
10-08 19:54:04.442  2809  2832 E AndroidRuntime: Process: com.myapplication, PID: 2809
10-08 19:54:04.442  2809  2832 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'n.IsAndroid'), stack:
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@766:85
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@765:196
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@764:352
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@763:85
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@762:85
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@758:395
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@755:2308
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@545:2281
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@544:85
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@543:263
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@407:402
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@406:85
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@405:227
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@404:2236
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@403:85
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@402:331
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@401:204
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@398:67
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@397:30
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@396:177
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@395:852
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@394:1326
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@392:240
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@391:2931
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@390:85
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@389:1018
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@388:85
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@7:156
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: <unknown>@6:30
10-08 19:54:04.442  2809  2832 E AndroidRuntime: v@2:1474
10-08 19:54:04.442  2809  2832 E AndroidRuntime: d@2:876
10-08 19:54:04.442  2809  2832 E AndroidRuntime: global code@1636:4
10-08 19:54:04.442  2809  2832 E AndroidRuntime: 
10-08 19:54:04.442  2809  2832 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
10-08 19:54:04.442  2809  2832 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-08 19:54:04.442  2809  2832 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
10-08 19:54:04.442  2809  2832 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
10-08 19:54:04.442  2809  2832 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-08 19:54:04.442  2809  2832 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
10-08 19:54:04.442  2809  2832 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-08 19:54:04.442  2809  2832 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
10-08 19:54:04.442  2809  2832 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-08 19:54:04.442  2809  2832 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
10-08 19:54:04.442  2809  2832 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
10-08 19:54:04.444  1529  4915 W ActivityManager:   Force finishing activity com.myapplication/.MainActivity
```

**Comment by Zeroxys** [comment]
I have the same behavior, any new with this?

**Comment by keremoge** [comment]
any solution yet?

**Comment by dunggnguyen** [comment]
I have same problem, anyone have solution? Thansk so much!
