### ISSUE TITLE
JitsiMeet.call(url, userInfo); crush Android App

### ISSUE THREAD

**Issue by shay-te** [skrafft/react-native-jitsi-meet#251]
Hello all trying to call but the entire application crash. 

```java
	13:54:47.507	unknown:ReactNative		CatalystInstanceImpl caught native exception
com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'E.SECURITY_LEVEL_ANY'), stack:
<unknown>@441:1268
v@2:1473
<unknown>@423:157
v@2:1473
<unknown>@408:130
v@2:1473
<unknown>@407:126
v@2:1473
<unknown>@406:174
v@2:1473
<unknown>@6:57
v@2:1473
d@2:875
global code@1017:3

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:923)

	13:54:47.507	unknown:DisabledDevSupportManager		Caught exception
com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'E.SECURITY_LEVEL_ANY'), stack:
<unknown>@441:1268
v@2:1473
<unknown>@423:157
v@2:1473
<unknown>@408:130
v@2:1473
<unknown>@407:126
v@2:1473
<unknown>@406:174
v@2:1473
<unknown>@6:57
v@2:1473
d@2:875
global code@1017:3

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:923)

	13:54:47.507	AndroidRuntime		FATAL EXCEPTION: mqt_native_modules
Process: com.objectivelove, PID: 24141
com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'E.SECURITY_LEVEL_ANY'), stack:
<unknown>@441:1268
v@2:1473
<unknown>@423:157
v@2:1473
<unknown>@408:130
v@2:1473
<unknown>@407:126
v@2:1473
<unknown>@406:174
v@2:1473
<unknown>@6:57
v@2:1473
d@2:875
global code@1017:3

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:923)

	13:54:47.509	JitsiMeetSDK		JitsiMeetUncaughtExceptionHandler FATAL ERROR
com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'E.SECURITY_LEVEL_ANY'), stack:
<unknown>@441:1268
v@2:1473
<unknown>@423:157
v@2:1473
<unknown>@408:130
v@2:1473
<unknown>@407:126
v@2:1473
<unknown>@406:174
v@2:1473
<unknown>@6:57
v@2:1473
d@2:875
global code@1017:3

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:923)

com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'E.SECURITY_LEVEL_ANY'), stack:
<unknown>@441:1268
v@2:1473
<unknown>@423:157
v@2:1473
<unknown>@408:130
v@2:1473
<unknown>@407:126
v@2:1473
<unknown>@406:174
v@2:1473
<unknown>@6:57
v@2:1473
d@2:875
global code@1017:3

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:923)

	13:54:48.008	MDD		DownloadProgressMonitor: Can't find file group for uri: android://com.google.android.googlequicksearchbox/files/sharedminusonemodule/shared/SharedMinusOneData.pb.tmp
```

**Comment by devteamtalkag1** [comment]
I have the same issue with the code from the example App !

```
React Native : ^0.63.3
"react-native-jitsi-meet": "^2.1.1",

```


```class Jitsi extends React.Component {

  constructor(props) {
    super(props);
  }

  componentDidMount() {
    console.log('Jitsi Call');
      
      setTimeout(() => {
        const url = 'https://meet.jit.si/ceciestunereunion'; // can also be only room name and will connect to jitsi meet servers
        const userInfo = { displayName: 'User', email: 'user@example.com', avatar: 'https:/gravatar.com/avatar/abc123' };
        JitsiMeet.call(url, userInfo);
        /* You can also use JitsiMeet.audioCall(url) for audio only call */
        /* You can programmatically end the call with JitsiMeet.endCall() */
      }, 1000);
  }

  componentWillUnmount() {
    JitsiMeet.endCall();
  }

  onConferenceTerminated = (nativeEvent) => {
    /* Conference terminated event */
    console.log('Conference terminated event')
  }

  onConferenceJoined = (nativeEvent)=> {
    /* Conference joined event */
    console.log('Conference joined event')
  }

  onConferenceWillJoin = (nativeEvent) => {
    /* Conference will join event */
    console.log('Conference will join event')
  }
  render() {
    return (
      <View style={{
        flex: 1,
        backgroundColor: 'black'
        }}>
        <JitsiMeetView style={{ flex: 1, height: '100%', width: '100%' }} />
      </View>
    );
  }
  
}```

**Comment by alexandrtovmach** [comment]
Figured out the problem and right now it works for me in development and build release apk. Full diff of my changes you can find [here](https://gist.github.com/alexandrtovmach/f0205dc5af196f6df1e7a6311f23a42f).

1. Follow [installation guide](https://github.com/skrafft/react-native-jitsi-meet#install) from this repo README
2. Downgrade `@react-native-community/netinfo`to *4.7.0*
3. Add next attributes (if not exist) to `application` tag in _android/app/src/debug/AndroidManifest.xml_
  ```
  android:allowBackup="true" tools:replace="android:allowBackup"
  ```
4. Add following attributes (if not exist) to `application` tag in _android/app/src/main/AndroidManifest.xml_
  ```
  tools:replace="android:allowBackup"
  ```
5. Add following attributes (if not exist) to `manifest` tag in _android/app/src/main/AndroidManifest.xml_
  ```
  xmlns:tools="http://schemas.android.com/tools"
  ```
6. Add "packagingOptions" to _android/app/build.gradle_
  ```
  packagingOptions {
    exclude 'META-INF/react-native-webview_release.kotlin_module'
  }
  ```
7. Make sure that you did the [last step from installation guide](https://github.com/skrafft/react-native-jitsi-meet#side-note), and then, add "debugImplementation" in a similar way:
  ```
  debugImplementation(project(':react-native-jitsi-meet')) {
    exclude group: 'com.facebook',module:'hermes'
  }
  ```

Possible fix for:
- https://github.com/skrafft/react-native-jitsi-meet/issues/244
- https://github.com/skrafft/react-native-jitsi-meet/issues/243
- https://github.com/skrafft/react-native-jitsi-meet/issues/217
- https://github.com/skrafft/react-native-jitsi-meet/issues/133

**Comment by nanhlua96** [comment]
@alexandrtovmach after trying to do it, something still work abnormal.
- start a call (without member in channel) the screen still black (not display any button) until someone appears.
- on calling (have members in channel), there is no button to cancel or mute the call.
- after call (everyone leave the channel), buttons appear but nothing on press or console error `Did not expect event target to be a number. Should have been a native component`

**Comment by alexandrtovmach** [comment]
@nanhlua96 I believe things that you have is not related to "Android crash issue", so can't suggest anything here

**Comment by nanhlua96** [comment]
@alexandrtovmach thanks,
I also try another way and it not require downgrade netinfo package
that change minSdkVersion and tools.build:gradle in android/build.gradle
![Screen Shot 2021-05-06 at 11 11 59](https://user-images.githubusercontent.com/67305927/117240815-e3adb080-ae5b-11eb-810d-8bdf67a062f7.png)
and in android/app/build.gradle just need
```
implementation ('org.jitsi.react:jitsi-meet-sdk:3.1.+') {
        exclude group: 'com.facebook.react', module:'react-native-vector-icons'
        exclude group: 'com.facebook.react', module:'react-native-webview'
        exclude group: 'com.facebook.react', module:'react-native-youtube'
        exclude group: 'com.facebook.react', module:'react-native-community-async-storage'
        // exclude group: 'com.facebook.react', module:'react-native-linear-gradient'
        exclude group: 'com.facebook.react', module:'react-native-background-timer'
        exclude group: 'com.facebook', module:'hermes'
        transitive = true
    }
```

**Comment by alexandrtovmach** [comment]
@nanhlua96 is that works for runtime and release?

**Comment by nanhlua96** [comment]
@alexandrtovmach I just test on simulator and still working with those unresponsible buttons, but I am you can test it on real devices.

**Comment by nanhlua96** [comment]
I face with some change in metro config that the old blacklist has removed
so I replace with exclusion list but i don't really know it correct or not
```
const blacklist = require('metro-config/src/defaults/exclusionList');
...
resolver: {
      blacklistRE: blacklist([
        /ios\/Pods\/JitsiMeetSDK\/Frameworks\/JitsiMeet.framework\/assets\/node_modules\/react-native\/.*/,
      ]),
...
```

**Comment by alexandrtovmach** [comment]
To be sure that solution form https://github.com/skrafft/react-native-jitsi-meet/issues/251#issuecomment-833210944 works, you need to run app in real-time (emulator), and also compile an APK and run it too. Because I found it a bit annoying when I though that I fixed the issue, and then everything fails on release build
