### ISSUE TITLE
React Native version mismatch.

### ISSUE THREAD

**Issue by nitis19286** [skrafft/react-native-jitsi-meet#272]
Hello,
I upgraded react-native 0.59.10 -> 0.62
iOS no problem but on android exception error
```
E/ReactNativeJS: React Native version mismatch.
    
    JavaScript version: 0.59.10
    Native version: 0.62.2
    
    Make sure that you have rebuilt the native code. If the problem persists try clearing the Watchman and packager caches with `watchman watch-del-all && react-native start --reset-cache`.
E/unknown:ReactNative: console.error: "React Native version mismatch.
    
    JavaScript version: 0.59.10
    Native version: 0.62.2
    
    Make sure that you have rebuilt the native code. If the problem persists try clearing the Watchman and packager caches with `watchman watch-del-all && react-native start --reset-cache`.", stack:
    checkVersions@130:306
    <unknown>@129:63
    h@2:1670
    <unknown>@114:92
    h@2:1670
    d@2:868
    global code@1687:4
V/FA: Activity resumed, time: 4300830272
E/ReactNativeJS: null is not an object (evaluating 't.languages')
E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
I/ReactNativeJS: BaseComponent _handleAppStateChange
I/ReactNativeJS: You can use the camera
I/ReactNativeJS: You can use the mic
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: th.go.chulalongkornhospital.chulacare, PID: 27828
    com.facebook.react.common.JavascriptException: null is not an object (evaluating 't.languages'), stack:
    <unknown>@406:191
    h@2:1670
    <unknown>@404:154
    h@2:1670
    <unknown>@402:3679
    h@2:1670
    <unknown>@401:194
    h@2:1670
    <unknown>@396:1603
    h@2:1670
    <unknown>@395:218
    h@2:1670
    <unknown>@389:1118
    h@2:1670
    <unknown>@388:192
    h@2:1670
    <unknown>@387:121
    h@2:1670
    <unknown>@11:78
    h@2:1670
    d@2:868
    global code@1688:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:47)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:224)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    com.facebook.react.common.JavascriptException: null is not an object (evaluating 't.languages'), stack:
    <unknown>@406:191
    h@2:1670
    <unknown>@404:154
    h@2:1670
    <unknown>@402:3679
    h@2:1670
    <unknown>@401:194
    h@2:1670
    <unknown>@396:1603
    h@2:1670
    <unknown>@395:218
    h@2:1670
    <unknown>@389:1118
    h@2:1670
    <unknown>@388:192
    h@2:1670
    <unknown>@387:121
    h@2:1670
    <unknown>@11:78
    h@2:1670
    d@2:868
    global code@1688:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:47)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:224)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
    
    com.facebook.react.common.JavascriptException: null is not an object (evaluating 't.languages'), stack:
    <unknown>@406:191
    h@2:1670
    <unknown>@404:154
    h@2:1670
    <unknown>@402:3679
    h@2:1670
    <unknown>@401:194
    h@2:1670
    <unknown>@396:1603
    h@2:1670
    <unknown>@395:218
    h@2:1670
    <unknown>@389:1118
    h@2:1670
    <unknown>@388:192
    h@2:1670
    <unknown>@387:121
    h@2:1670
    <unknown>@11:78
    h@2:1670
    d@2:868
    global code@1688:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:47)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:224)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by saheemhussainchicmic** [comment]
@nitis19286 How was the issue solved? I am facing similar issue. Js version: 0.63.4 Native version: 0.66.4

**Comment by letaptravek** [comment]
@saheemhussainchicmic Hello, were you able to solve this issue?. I am facing same issue, version
 mismatch JS version 0.63.3 and Native version 0.66.4.

I am facing same issue for any react native version other than 0.66.4.

**Comment by ajmalbinansari** [comment]
@saheemhussainchicmic  @letaptravek  Hi, have you solved this issue. I am facing the same one. JS version 0.64.2 & Native version 0.68.1. I cannot really update my RN version right now. Any solutions?

**Comment by Symous** [comment]
@nitis19286  @saheemhussainchicmic  @letaptravek  any progress here friend?
