### ISSUE TITLE
RNCNetInfo.getCurrentState got 2 arguments, expected 3 FATAL EXCEPTION: mqt_native_modules

### ISSUE THREAD

**Issue by TarekBaccari** [skrafft/react-native-jitsi-meet#277]
i m using react-native-jitsi-meet 
when invoking the JitsiMeetView component , a crash is is accrued

**information 
react native 0.63.4
"@react-native-community/netinfo": "^5.9.5"
hermes disabled** 

> i tried to resolve the problem as indicated here (https://github.com/jitsi/jitsi-meet/issues/6812) but it doesn't work for me 

FATAL EXCEPTION: mqt_native_modules

com.facebook.react.bridge.NativeArgumentsParseException: RNCNetInfo.getCurrentState got 2 arguments, expected 3

FATAL EXCEPTION: mqt_native_modules
Process: com.diama, PID: 13246
com.facebook.react.bridge.NativeArgumentsParseException: RNCNetInfo.getCurrentState got 2 arguments, expected 3
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:214)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:919)

**Comment by UnSensei** [comment]
implementation(project(':react-native-jitsi-meet')) {
      exclude group: 'com.facebook.react',module:'react-native-locale-detector'
      exclude group: 'com.facebook.react',module:'react-native-vector-icons'
      // Un-comment below if using hermes
      //exclude group: 'com.facebook',module:'hermes'
      // Un-comment any packages below that you have added to your project to prevent `duplicate_classes` errors
      //exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
      //exclude group: 'com.facebook.react',module:'react-native-community_netinfo'
      //exclude group: 'com.facebook.react',module:'react-native-svg'
      //exclude group: 'com.facebook.react',module:'react-native-fetch-blob'
      //exclude group: 'com.facebook.react',module:'react-native-webview'
      //exclude group: 'com.facebook.react',module:'react-native-linear-gradient'
      //exclude group: 'com.facebook.react',module:'react-native-sound'
    }

Try this in your build.gradle. uncomment the packages you use in your project

**Comment by TarekBaccari** [comment]
i already do  , but it doesn't resolve the problem , for the moment i resolved this issue by uninstalling this package from my app , although i excluded it (exclude group: 'com.facebook.react',module:'@react-native-community/netinfo') but it steal cause the crash , i need to use this package

**Comment by TarekBaccari** [comment]
> implementation(project(':react-native-jitsi-meet')) {
> exclude group: 'com.facebook.react',module:'react-native-locale-detector'
> exclude group: 'com.facebook.react',module:'react-native-vector-icons'
> // Un-comment below if using hermes
> //exclude group: 'com.facebook',module:'hermes'
> // Un-comment any packages below that you have added to your project to prevent `duplicate_classes` errors
> //exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
> //exclude group: 'com.facebook.react',module:'react-native-community_netinfo'
> //exclude group: 'com.facebook.react',module:'react-native-svg'
> //exclude group: 'com.facebook.react',module:'react-native-fetch-blob'
> //exclude group: 'com.facebook.react',module:'react-native-webview'
> //exclude group: 'com.facebook.react',module:'react-native-linear-gradient'
> //exclude group: 'com.facebook.react',module:'react-native-sound'
> }
> 
> Try this in your build.gradle. uncomment the packages you use in your project

i already do , but it doesn't resolve the problem , for the moment i resolved this issue by uninstalling this package ('@react-native-community/netinfo) from my app , although i excluded it (exclude group: 'com.facebook.react',module:'@react-native-community/netinfo') but it steal cause the crash , so i uninstall it for a while ,but i need to use this package after :/
