### ISSUE TITLE
Error while updating property 'streamURL' of a view managed by: RTCVideoView 

### ISSUE THREAD

**Issue by rizwanatta** [skrafft/react-native-jitsi-meet#32]
**ONLY ! on android!** 

**It works fine on IOS!**

Update to Android version 28 and webrtc is not working.
2019-04-22 16:49:21.073 13561-13561/jp.co.neolab.calling.dev E/unknown:ViewManager: Error while updating prop streamURL java.lang.reflect.InvocationTargetException at java.lang.reflect.Method.invoke(Native Method) at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83) at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132) at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51) at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37) at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:265) at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200) at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1109) at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1080) at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166) at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:869) at android.view.Choreographer.doCallbacks(Choreographer.java:683) at android.view.Choreographer.doFrame(Choreographer.java:616) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6077) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) Caused by: java.lang.IllegalArgumentException: Could not find @ReactModule annotation in com.oney.WebRTCModule.WebRTCModule at com.facebook.react.bridge.CatalystInstanceImpl.getNameFromAnnotation(CatalystInstanceImpl.java:438) at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:427) at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:128) at com.oney.WebRTCModule.WebRTCView.getVideoTrackForStreamURL(WebRTCView.java:231) at com.oney.WebRTCModule.WebRTCView.setStreamURL(WebRTCView.java:541) at com.oney.WebRTCModule.RTCVideoViewManager.setStreamURL(RTCVideoViewManager.java:59) at java.lang.reflect.Method.invoke(Native Method)  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)  at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)  at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:265)  at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1109)  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1080)  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:869)  at android.view.Choreographer.doCallbacks(Choreographer.java:683)  at android.view.Choreographer.doFrame(Choreographer.java:616)  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)  at android.os.Handler.handleCallback(Handler.java:751)  at android.os.Handler.dispatchMessage(Handler.java:95)  at android.os.Looper.loop(Looper.java:154)  at android.app.ActivityThread.main(ActivityThread.java:6077)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)  2019-04-22 16:49:21.073 13561-13561/jp.co.neolab.calling.dev E/unknown:ReactNative: Exception in native call com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'streamURL' of a view managed by: RTCVideoView at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:95) at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132) at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51) at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37) at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:265) at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200) at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1109) at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1080) at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166) at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:869) at android.view.Choreographer.doCallbacks(Choreographer.java:683) at android.view.Choreographer.doFrame(Choreographer.java:616) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6077) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) Caused by: java.lang.reflect.InvocationTargetException at java.lang.reflect.Method.invoke(Native Method) at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83) at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)  at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)  at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:265)  at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1109)  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1080)  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:869)  at android.view.Choreographer.doCallbacks(Choreographer.java:683)  at android.view.Choreographer.doFrame(Choreographer.java:616)  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)  at android.os.Handler.handleCallback(Handler.java:751)  at android.os.Handler.dispatchMessage(Handler.java:95)  at android.os.Looper.loop(Looper.java:154)  at android.app.ActivityThread.main(ActivityThread.java:6077)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)  Caused by: java.lang.IllegalArgumentException: Could not find @ReactModule annotation in com.oney.WebRTCModule.WebRTCModule at com.facebook.react.bridge.CatalystInstanceImpl.getNameFromAnnotation(CatalystInstanceImpl.java:438) at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:427) at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:128) at com.oney.WebRTCModule.WebRTCView.getVideoTrackForStreamURL(WebRTCView.java:231) at com.oney.WebRTCModule.WebRTCView.setStreamURL(WebRTCView.java:541) at com.oney.WebRTCModule.RTCVideoViewManager.setStreamURL(RTCVideoViewManager.java:59) at java.lang.reflect.Method.invoke(Native Method)  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)  at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)  at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:265)  at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1109)  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1080)  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:869)  at android.view.Choreographer.doCallbacks(Choreographer.java:683)  at android.view.Choreographer.doFrame(Choreographer.java:616)  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)  at android.os.Handler.handleCallback(Handler.java:751)  at android.os.Handler.dispatchMessage(Handler.java:95)  at android.os.Looper.loop(Looper.java:154)  at android.app.ActivityThread.main(ActivityThread.java:6077)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
![56495312-95047680-651f-11e9-949d-9b68e3700da2](https://user-images.githubusercontent.com/22873095/57147297-b0edff00-6de0-11e9-8ddd-25d57468746d.png)

Screen Shot 2019-04-22 at 4 49 51 PM

 
<img width="1799" alt="56495304-903fc280-651f-11e9-977f-bac575952e20" src="https://user-images.githubusercontent.com/22873095/57147012-15f52500-6de0-11e9-94eb-18993613782e.png">

**Comment by zayedelfasa** [comment]
i have same problem here.

**Comment by varun1996** [comment]
I am also facing the same issue here. I have tried to downgrade react-native version to 0.58.6 but still I am getting the same error

**Comment by skrafft** [comment]
Hi all, 

Do you have this problem on emulator or also on real devices ? I've seen issues with react-native-webrtc on emulator. It's better to test on real devices.

**Comment by rizwanatta** [comment]
well it works just fine on iOS to iOS in REAL DEVICES!     but on android its giving this crash while testing on real devices

**Comment by rizwanatta** [comment]
the issue wasn't there when i coded it first  with the RN version 0.56 after upgrade to 0.58 it was still in working but now on 0.59+ it is crashing only on android side!

**Comment by varun1996** [comment]
Yes this issue is both in emulator and real devices in android

**Comment by varun1996** [comment]
It is not working in 0.58 version of React Native I have tried it

**Comment by varun1996** [comment]
on real android device I am having this error (found in adblogcat) 
 NativeLibrary: Failed to load native library: jingle_peerconnection_so.so

**Comment by saadqbal** [comment]
Update your react-native-fast-image library

**Comment by skrafft** [comment]
Hi all, 

I just published v1.2.0 of the lib. It uses the new jitsi-meet 2.1.0 sdk on Android and on iOS. It's been tested on our side with RN 0.59.5 and we did not have any error, neither on iOS nor Android.

Are you able to test this new version and give your feedback if it fixes this specific error ?

Thanks

**Comment by rizwanatta** [comment]
> Hi all,
> 
> I just published v1.2.0 of the lib. It uses the new jitsi-meet 2.1.0 sdk on Android and on iOS. It's been tested on our side with RN 0.59.5 and we did not have any error, neither on iOS nor Android.
> 
> Are you able to test this new version and give your feedback if it fixes this specific error ?
> 
> Thanks

looking into it! will respond ASAP

**Comment by varun1996** [comment]
Thanks!!. Now its working fine

**Comment by zayedelfasa** [comment]
I am so sorry because i have modified this node-modules on jitsi 2.0 for my project and its work fine on my android devices. nice project!

**Comment by rizwanatta** [comment]
its working now after upgrading to 1.2.0 . thanks

**Comment by reactnativedeveloper1** [comment]
> new jitsi-meet 2.1.0
how to use this can you explain
