### ISSUE TITLE
I have integrated the latest version 3.1.0 of the software and the latest SDK version 5.1.0 into my project. The build process completes successfully without any errors. However, when the application is running and reaches 100% completion, a crash occurs, and the following error message is displayed(It will be shown in the comment)

### ISSUE THREAD

**Issue by prasant1123** [skrafft/react-native-jitsi-meet#439]
Here is the error log :java.lang.RuntimeException: Unable to get provider io.invertase.firebase.app.ReactNativeFirebaseAppInitProvider: java.lang.ClassNotFoundException: Didn't find class "io.invertase.firebase.app.ReactNativeFirebaseAppInitProvider" on path: DexPathList[[zip file "/data/app/~~JxGeHaQMJUsT6ZMHS5WB9g==/com.icourt.app-fvk6ii_QcA6gg3JCpQ5WFQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~JxGeHaQMJUsT6ZMHS5WB9g==/com.icourt.app-fvk6ii_QcA6gg3JCpQ5WFQ==/lib/arm64, /data/app/~~JxGeHaQMJUsT6ZMHS5WB9g==/com.icourt.app-fvk6ii_QcA6gg3JCpQ5WFQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
 at android.app.ActivityThread.installProvider(ActivityThread.java:7865)
 at android.app.ActivityThread.installContentProviders(ActivityThread.java:7371)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7104)
 at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:211)
 at android.os.Looper.loop(Looper.java:300)
 at android.app.ActivityThread.main(ActivityThread.java:8289)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.ClassNotFoundException: Didn't find class "io.invertase.firebase.app.ReactNativeFirebaseAppInitProvider" on path: DexPathList[[zip file "/data/app/~~JxGeHaQMJUsT6ZMHS5WB9g==/com.icourt.app-fvk6ii_QcA6gg3JCpQ5WFQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~JxGeHaQMJUsT6ZMHS5WB9g==/com.icourt.app-fvk6ii_QcA6gg3JCpQ5WFQ==/lib/arm64, /data/app/~~JxGeHaQMJUsT6ZMHS5WB9g==/com.icourt.app-fvk6ii_QcA6gg3JCpQ5WFQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
 at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
 at android.app.ActivityThread.installProvider(ActivityThread.java:7849)
 ... 11 more

**Comment by EDible-Dev** [comment]
@prasant1123 - I am still trying to get the app to build.  As soon as I include the react-native-jitsi-meet package (2.3.1), it does not build any more.  May I ask what version of react-native you are using?   And when you said 3.1.0, which package are you referring to?  Thanks!
