### ISSUE TITLE
React Native 0.60 Android not running

### ISSUE THREAD

**Issue by djorkaeffalexandre** [skrafft/react-native-jitsi-meet#52]
I followed all steps on a blank project with:
```
"react": "16.8.6",
"react-native": "0.60.5",
"react-native-jitsi-meet": "^1.2.0"
```
When I click to open Jitsi Activity get follow error:
`java.lang.AssertionError: Activity needs to be set if initial lifecycle state is resumed` 

When I try with `react-native: 0.59.8` it works, but my app is in 0.60 :( help-me

**Comment by Rana-Mohit** [comment]
Hi, 
I also down grade to version react-native: 0.59.8, but in my case it is not working. Getting this error after calling this method on button click.
Method:--
function initiateVideoCall  ()  {
   JitsiMeet.initialize();
  JitsiMeetEvents.addListener('CONFERENCE_LEFT', (data) => {
    console.log('CONFERENCE_LEFT');
  });
  setTimeout(() => {
    JitsiMeet.call('https://meet.jit.si/roomName');
  }, 1000);
};

Error Logs :--

2019-09-05 11:39:00.573 19086-19259/com.jitsisdk3 E/ReactNativeJS: Application App has not been registered.
    
    Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
    If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').
    
    This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.
    
    
    
    --------- beginning of crash
2019-09-05 11:39:00.594 19086-19260/com.jitsisdk3 E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.jitsisdk3, PID: 19086
    com.facebook.react.common.JavascriptException: Application App has not been registered.
    
    Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
    If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').
    
    This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.
    
    , stack:
    runApplication@333:1932
    value@28:3311
    <unknown>@28:822
    value@28:2565
    value@28:794
    value@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
2019-09-05 11:39:00.598 1801-7720/? W/ActivityManager:   Force finishing activity com.jitsisdk3/com.reactnativejitsimeet.JitsiMeetNavigatorActivity

Any help will be appreciated thanks in advance.

**Comment by skrafft** [comment]
Duplicates #55
