### ISSUE TITLE
Could not find org.jitsi.react:jitsi-meet-sdk:2.3.0

### ISSUE THREAD

**Issue by jean-ben-guigui** [skrafft/react-native-jitsi-meet#67]
RN : 0.61.2
react-native-jitsi-meet: 2.0.1

Hello,
After I created a project using `react-native init`, I added your library `npm install react-native-jitsi-meet --save` then I added followed the readMe and completed my metro.config.js

When I run react-native run-android, I get the following error:

     * What went wrong:
    Could not determine the dependencies of task ':app:preDebugBuild'.
    > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
      > Could not find org.jitsi.react:jitsi-meet-sdk:2.3.0.
        Searched in the following locations:
          - file:/Users/swl/.m2/repository/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.pom
          - file:/Users/swl/.m2/repository/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.jar
          - file:/Users/swl/tests/MonSisra/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.pom
          - file:/Users/swl/tests/MonSisra/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.jar
          - file:/Users/swl/tests/MonSisra/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.pom
          - file:/Users/swl/tests/MonSisra/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.jar
          - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.pom
          - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.jar
          - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.pom
          - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.jar
          - https://jitpack.io/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.pom
          - https://jitpack.io/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.jar
        Required by:
            project :app > project :react-native-jitsi-meet

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 3s

    error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
    Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

    FAILURE: Build failed with an exception.

    * What went wrong:
    Could not determine the dependencies of task ':app:preDebugBuild'.
    > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
      > Could not find org.jitsi.react:jitsi-meet-sdk:2.3.0.
        Searched in the following locations:
          - file:/Users/swl/.m2/repository/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.pom
          - file:/Users/swl/.m2/repository/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.jar
          - file:/Users/swl/tests/MonSisra/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.pom
          - file:/Users/swl/tests/MonSisra/node_modules/react-native/android/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.jar
          - file:/Users/swl/tests/MonSisra/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.pom
          - file:/Users/swl/tests/MonSisra/node_modules/jsc-android/dist/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.jar
          - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.pom
          - https://dl.google.com/dl/android/maven2/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.jar
          - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.pom
          - https://jcenter.bintray.com/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.jar
          - https://jitpack.io/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.pom
          - https://jitpack.io/org/jitsi/react/jitsi-meet-sdk/2.3.0/jitsi-meet-sdk-2.3.0.jar
        Required by:
            project :app > project :react-native-jitsi-meet

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 3s

        at checkExecSyncError (child_process.js:601:13)
        at execFileSync (child_process.js:621:13)
        at runOnAllDevices (/Users/swl/tests/MonSisra/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
        at buildAndRun (/Users/swl/tests/MonSisra/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
        at then.result (/Users/swl/tests/MonSisra/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

Would you have an idea of what I'm doing wrong?

**Comment by NielsDom** [comment]
I have same problem

**Comment by saadrehman013** [comment]
I am also stuck with the same issue. Moreover, I didn't find any of the code in android gradle files that is supposed to be there because of auto-linking. Do we still have to put it there maually or its a bug. Any update?

RN: 0.61.2
jetsi: 2.0.1

**Comment by biphan1008** [comment]
tôi tìm thấy 1 trong những sdk trên ở đây https://github.com/jitsi/jitsi-maven-repository/tree/master/releases/org/jitsi/react/jitsi-meet-sdk/2.3.0 nhưng tôi không biết phải đặt chúng vào đâu trong dự án của tôi.

**Comment by msantang78** [comment]
To fix the app crash I changed in the android/build.gradle:
`implementation ('org.jitsi.react:jitsi-meet-sdk:2.3.0') {`
To
`implementation ('org.jitsi.react:jitsi-meet-sdk:2.4.0') {`

It works perfect on dev mode but it crashes on the prod build
RN: 0.61.2

**Comment by jean-ben-guigui** [comment]
Is your problem in prod build the same as #72 ?

**Comment by jean-ben-guigui** [comment]
Do you have the same problem in prod build as #72 or as #70 ?

**Comment by msantang78** [comment]
I tried a new clean RN app with RN 0.61.2 and react-native-jitsi-meet (changing again the SDK to 2.4.0) It worked on dev mode but on production I have the #70 error.

In my full app, the error in the production build is different
I'm receiving an error in the react-native-gesture-handler used by the react-navigation package

But jitsi doesn't use that package, maybe some issue with auto-linked packages and the SDK?

![prod_error](https://user-images.githubusercontent.com/5406452/67687359-f4cc5600-f976-11e9-92ff-f95749016f75.png)

**Comment by skrafft** [comment]
I've released a new version 2.0.2 with SDK 2.4.0.
For your problem in release, can you try the following:

- In `android/app/build.gradle`, add/replace the following lines:

```
project.ext.react = [
    entryFile: "index.js",
    bundleAssetName: "app.bundle",
]
```

- In `android/app/src/main/java/com/xxx/MainApplication.java` add/replace the following methods:

```
    @Override
    protected String getJSMainModuleName() {
      return "index";
    }

    @Override
    protected @Nullable String getBundleAssetName() {
      return "app.bundle";
    }
```

**Comment by jean-ben-guigui** [comment]
I appreciate the new version, thanks!

Thanks for helping, I eventually got it to work 👍 
I did what you told me. But I also added the following in `android/app/src/main/java/com/xxx/MainApplication.java`:

    import androidx.annotation.Nullable;

**Comment by srvkataria** [comment]
> I've released a new version 2.0.2 with SDK 2.4.0.
> For your problem in release, can you try the following:
> 
>     * In `android/app/build.gradle`, add/replace the following lines:
> 
> 
> ```
> project.ext.react = [
>     entryFile: "index.js",
>     bundleAssetName: "app.bundle",
> ]
> ```
> 
>     * In `android/app/src/main/java/com/xxx/MainApplication.java` add/replace the following methods:
> 
> 
> ```
>     @Override
>     protected String getJSMainModuleName() {
>       return "index";
>     }
> 
>     @Override
>     protected @Nullable String getBundleAssetName() {
>       return "app.bundle";
>     }
> ```

I was also getting this error in the release mode. Your solution worked seamlessly! 
Thanks a ton!

**Comment by acostalima** [comment]
@skrafft why does the bundle name has to be overridden?

**Comment by skrafft** [comment]
As the jitsi meet sdk is written is React Native as well, it already uses app.bundle for its own code. So we have to override the bundle name to avoid conflicts and one overwriting the other.

**Comment by acostalima** [comment]
@skrafft indeed, makes sense! Thanks for the clarification.
