### ISSUE TITLE
TypeError: null is not an object (evaluating 'n.default.configureProps') jitsi meet

### ISSUE THREAD

**Issue by MeghsP** [skrafft/react-native-jitsi-meet#87]
Hi @skrafft,

I updated my app with new implementation of jisti-meet. Now, everytime I navigate to my VideoCall screen, app always crash with below logs:

```
ReactNativeJS: TypeError: null is not an object (evaluating 'n.default.configureProps')
2019-11-28 20:35:43.662 27472-28267/? E/ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
    
    --------- beginning of crash
2019-11-28 20:35:43.685 27472-28268/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.telehealthcare, PID: 27472
    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'n.default.configureProps'), stack:
    s@555:2197
    <unknown>@555:2245
    v@2:1474
    <unknown>@500:734
    v@2:1474
    <unknown>@499:206
    v@2:1474
    <unknown>@498:271
    v@2:1474
    <unknown>@494:268
    v@2:1474
    <unknown>@493:1546
    v@2:1474
    <unknown>@383:171
    v@2:1474
    <unknown>@6:58
    v@2:1474
    d@2:876
    global code@1124:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
2019-11-28 20:35:43.689 27472-28268/? E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
```

Here is my package.json:

```
{
  "name": "LafiyaUpgrade",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "moment": "^2.24.0",
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-animatable": "^1.3.3",
    "react-native-card-stack-swiper": "^1.1.8",
    "react-native-cardview": "^2.0.5",
    "react-native-circular-action-menu": "^0.5.0",
    "react-native-contacts": "^4.0.3",
    "react-native-datepicker-dialog": "0.0.9",
    "react-native-elements": "^1.2.7",
    "react-native-expandable-section-list": "^1.0.7",
    "react-native-gesture-handler": "^1.5.1",
    "react-native-jitsi-meet": "^2.0.2",
    "react-native-loader": "^1.2.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-material-textfield": "^0.16.1",
    "react-native-parallax-scroll-view": "^0.21.3",
    "react-native-reanimated": "^1.4.0",
    "react-native-swipeout": "^2.3.6",
    "react-native-tab-view": "^2.11.0",
    "react-native-table-component": "^1.2.1",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.0",
    "url-search-params": "^1.1.0"
  },
  "devDependencies": {
    "@babel/core": "7.7.2",
    "@babel/runtime": "7.7.2",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.6.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.3",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

App level build.gradle:

```
apply plugin: "com.android.application"

import com.android.build.OutputFile


project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

def jscFlavor = 'org.webkit:android-jsc:+'

def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.telehealcare"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-reanimated')
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-contacts')
    implementation project(':react-native-cardview')
    implementation project(':react-native-jitsi-meet')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
//    implementation ('org.jitsi.react:jitsi-meet-sdk:2.4.0') { transitive = true }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

```
Project level build.gradle:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.0"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven { // <---- Add this block
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```

VideoCallScreen.js:

```
import React from 'react';
import { View } from 'react-native';
import JitsiMeet, { JitsiMeetView } from 'react-native-jitsi-meet';

export default class VideoCallScreen extends React.Component {
  constructor(props) {
    super(props);
    this.onConferenceTerminated = this.onConferenceTerminated.bind(this);
    this.onConferenceJoined = this.onConferenceJoined.bind(this);
    this.onConferenceWillJoin = this.onConferenceWillJoin.bind(this);
  }

  componentDidMount() {
    setTimeout(() => {
      // this.setState({data:this.props.navigation.state.params.data});  
      const url = this.props.navigation.state.params.callUrl;
      var isAudio = this.props.navigation.state.params.isAudio;
      
      console.log("VideoCallScreen url: " + url+" & isAudio: " + isAudio);

      if(isAudio){
        JitsiMeet.audioCall(url);
      } else {
        JitsiMeet.call(url);
      }
      /* You can programmatically end the call with JitsiMeet.endCall() */
    }, 1000);
  }

  onConferenceTerminated(nativeEvent) {
    /* Conference terminated event */
    console.log('onConferenceTerminated');
  }

  onConferenceJoined(nativeEvent) {
    /* Conference joined event */
    console.log('onConferenceJoined');
  }

  onConferenceWillJoin(nativeEvent) {
    /* Conference will join event */
    console.log('onConferenceWillJoin');
  }

  render() {
    return (
      <View style={{ backgroundColor: 'black',flex: 1 }}>
        <JitsiMeetView onConferenceTerminated={this.onConferenceTerminated} onConferenceJoined={this.onConferenceJoined} onConferenceWillJoin={this.onConferenceWillJoin} style={{ flex: 1, height: '100%', width: '100%' }} />
      </View>
    );
  }
}

```
Code to navigate to VideoCallScreen:

```
var url = "https://myurl.shop/" + finalName;
    var {navigate} = this.props.navigation;
     navigate('VideoCallScreen', {callUrl:url, isAudio:this.state.isAudioEnable})
```

This issue appears on both debug as well as release build.

Please help me where I am going wrong and why this issue is occurs when I navigate to VideoCallScreen on button click?

**Comment by skrafft** [comment]
I think you did not follow steps 1 to 3 of this: https://github.com/skrafft/react-native-jitsi-meet#android-manual-install

The steps are mandatory otherwise Jitsi Meet is loading the wrong react native code

**Comment by skrafft** [comment]
No activity. Closing.

**Comment by hasgardee** [comment]
Finally fixed it. `react-native-codepush` was causing issues for me. try disabling it. codepush bundle name is different than app.bundle I guess. So, want to make both same to run codepush and react-native-jitsi-meet

**Comment by Santhosh1392** [comment]
This is how I am able to fix the issue.
I removed index.android.bundle from android/app/src/main/assets

Hope this may help someone

**Comment by AustynoChuks** [comment]
@skrafft

**Comment by AustynoChuks** [comment]
AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
03-26 20:24:13.369  5375  5531 E AndroidRuntime: Process: com.telemed, PID: 5375
03-26 20:24:13.369  5375  5531 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't(r(d[1])).default.Direction'), stack:
03-26 20:24:13.369  5375  5531 E AndroidRuntime: <unknown>@515:132
03-26 20:24:13.369  5375  5531 E AndroidRuntime: v@2:1473
03-26 20:24:13.369  5375  5531 E AndroidRuntime: <unknown>@507:809
03-26 20:24:13.369  5375  5531 E AndroidRuntime: v@2:1473
03-26 20:24:13.369  5375  5531 E AndroidRuntime: <unknown>@506:226
03-26 20:24:13.369  5375  5531 E AndroidRuntime: v@2:1473
03-26 20:24:13.369  5375  5531 E AndroidRuntime: <unknown>@505:312
03-26 20:24:13.369  5375  5531 E AndroidRuntime: v@2:1473
03-26 20:24:13.369  5375  5531 E AndroidRuntime: <unknown>@504:635
03-26 20:24:13.369  5375  5531 E AndroidRuntime: v@2:1473
03-26 20:24:13.369  5375  5531 E AndroidRuntime: <unknown>@503:84
03-26 20:24:13.369  5375  5531 E AndroidRuntime: v@2:1473
03-26 20:24:13.369  5375  5531 E AndroidRuntime: <unknown>@496:276
03-26 20:24:13.369  5375  5531 E AndroidRuntime: v@2:1473
03-26 20:24:13.369  5375  5531 E AndroidRuntime: <unknown>@495:186
03-26 20:24:13.369  5375  5531 E AndroidRuntime: v@2:1473
03-26 20:24:13.369  5375  5531 E AndroidRuntime: <unknown>@488:1498
03-26 20:24:13.369  5375  5531 E AndroidRuntime: v@2:1473
03-26 20:24:13.369  5375  5531 E AndroidRuntime: <unknown>@396:184
03-26 20:24:13.369  5375  5531 E AndroidRuntime: v@2:1473
03-26 20:24:13.369  5375  5531 E AndroidRuntime: <unknown>@6:57
03-26 20:24:13.369  5375  5531 E AndroidRuntime: v@2:1473
03-26 20:24:13.369  5375  5531 E AndroidRuntime: d@2:875
03-26 20:24:13.369  5375  5531 E AndroidRuntime: global code@1415:3
03-26 20:24:13.369  5375  5531 E AndroidRuntime:
03-26 20:24:13.369  5375  5531 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
03-26 20:24:13.369  5375  5531 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-26 20:24:13.369  5375  5531 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
03-26 20:24:13.369  5375  5531 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
03-26 20:24:13.369  5375  5531 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-26 20:24:13.369  5375  5531 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:888)
03-26 20:24:13.369  5375  5531 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
03-26 20:24:13.369  5375  5531 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
03-26 20:24:13.369  5375  5531 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:213)
03-26 20:24:13.369  5375  5531 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
03-26 20:24:13.369  5375  5531 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:929)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't(r(d[1])).default.Direction'), stack:
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@515:132
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@507:809
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@506:226
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@505:312
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@504:635
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@503:84
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@496:276
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@495:186
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@488:1498
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@396:184
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@6:57
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: d@2:875
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: global code@1415:3
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at java.lang.reflect.Method.invoke(Native Method)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at android.os.Handler.handleCallback(Handler.java:888)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at android.os.Handler.dispatchMessage(Handler.java:100)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at android.os.Looper.loop(Looper.java:213)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at java.lang.Thread.run(Thread.java:929)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't(r(d[1])).default.Direction'), stack:
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@515:132
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@507:809
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@506:226
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@505:312
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@504:635
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@503:84
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@496:276
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@495:186
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@488:1498
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@396:184
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: <unknown>@6:57
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: v@2:1473
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: d@2:875
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK: global code@1415:3
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at java.lang.reflect.Method.invoke(Native Method)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at android.os.Handler.handleCallback(Handler.java:888)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at android.os.Handler.dispatchMessage(Handler.java:100)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at android.os.Looper.loop(Looper.java:213)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
03-26 20:24:13.371  5375  5531 E JitsiMeetSDK:  at java.lang.Thread.run(Thread.java:929)

**Comment by AustynoChuks** [comment]
import React, { useEffect, useState } from 'react'
import { View, Text, StatusBar, TouchableOpacity } from 'react-native'
import JitsiMeet, { JitsiMeetView } from "react-native-jitsi-meet"

export default function(props){
    const [showJitsi, setShowJitsi] = useState(true)

    useEffect(() => {
        const url = "https://meet.jit.si/chuks_889";
        const userInfo = {
            email: "ewurumaugustine@gmail.com",
            displayName: "Augustine",
            avatar: 'https:/gravatar.com/avatar/abc123'
        }
        JitsiMeet.audioCall(url, userInfo)
    }, [1])

    const onConferenceWillJoin = () => { 
        console.log('will join')
    }
    const onConferenceTerminated = () => {
        console.log('terminated')
     }

    const onConferenceJoined = () => {
        console.log('joined')
        // setShowJitsi(false);
        setTimeout(() => {
            setShowJitsi(true)
        }, 100)
    };

    return (
        <View style={{flex:1}}>
            <JitsiMeetView
                onConferenceWillJoin={onConferenceWillJoin}
                onConferenceTerminated={onConferenceTerminated}
                onConferenceJoined={onConferenceJoined}
                style={{ flex: 1, height: '100%', width: '100%', backgroundColor: 'black' }}
            />
        </View>
    )
}

**Comment by hemant2capgemini** [comment]
I am also facing the same issue
`2022-06-28 08:30:29.097 17496-17560/com.awesomeproject E/ReactNativeJS: TypeError: null is not an object (evaluating 'o.call')
2022-06-28 08:30:29.105 17496-17560/com.awesomeproject E/ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
          This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
    
    --------- beginning of crash
2022-06-28 08:30:29.123 17496-17561/com.awesomeproject E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.awesomeproject, PID: 17496
    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'o.call'), stack:
    <unknown>@406:253
    h@2:1585
    <unknown>@405:119
    h@2:1585
    <unknown>@404:567
    h@2:1585
    <unknown>@403:674
    h@2:1585
    <unknown>@6:53
    h@2:1585
    d@2:958
    global code@555:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:923)
2022-06-28 08:30:29.123 17496-17561/com.awesomeproject E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'o.call'), stack:
    <unknown>@406:253
    h@2:1585
    <unknown>@405:119
    h@2:1585
    <unknown>@404:567
    h@2:1585
    <unknown>@403:674
    h@2:1585
    <unknown>@6:53
    h@2:1585
    d@2:958
    global code@555:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:923)
    
    com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'o.call'), stack:
    <unknown>@406:253
    h@2:1585
    <unknown>@405:119
    h@2:1585
    <unknown>@404:567
    h@2:1585
    <unknown>@403:674
    h@2:1585
    <unknown>@6:53
    h@2:1585
    d@2:958
    global code@555:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:923)`

Did not make out any solutions, Can anyone help here?

**Comment by TacticCoder** [comment]
Same here

**Comment by nppull** [comment]
> Same here

have you solution ?
I create new project without Reaminated v2 and work good, when add Reaminated v2 I get error.

**Comment by AndrewLutsenko** [comment]
`[features/app] Error(Error){"message":"Requiring module \"2503\", which threw an exception: TypeError: o.default.configureProps is not a function. (In 'o.default.configureProps(Object.keys(l),Object.keys(n))', 'o.default.configureProps' is undefined)","stack":"h@index.android.bundle:2:1477\nd@index.android.bundle:2:959\nc@index.android.bundle:2508:945\nindex.android.bundle:2508:1247\nindex.android.bundle:2506:2714\nindex.android.bundle:2499:183\nindex.android.bundle:2489:130\nindex.android.bundle:2490:668\nindex.android.bundle:2486:830\nindex.android.bundle:2485:992\nindex.android.bundle:2483:1590\nindex.android.bundle:2478:175\nindex.android.bundle:2455:1720\nindex.android.bundle:2436:1663\nindex.android.bundle:2423:2144\nu@index.android.bundle:2419:1631\nindex.android.bundle:2419:1898\nindex.android.bundle:2417:4181\nindex.android.bundle:2416:2615\nindex.android.bundle:2414:2944\nindex.android.bundle:2412:3822\nindex.android.bundle:2407:153\nindex.android.bundle:2396:2500\nindex.android.bundle:2393:254\nindex.android.bundle:2390:526\nindex.android.bundle:2389:330\nindex.android.bundle:2388:122\nindex.android.bundle:2380:209\nindex.android.bundle:2379:227\nindex.android.bundle:2357:401\nindex.android.bundle:1895:5946\nindex.android.bundle:2340:277\nindex.android.bundle:2339:674\nindex.android.bundle:2337:531\nindex.android.bundle:2335:6140\nindex.android.bundle:2331:1299\nindex.android.bundle:2329:703\nindex.android.bundle:2324:1661\nindex.android.bundle:2323:139\nindex.android.bundle:2322:363\nindex.android.bundle:2316:6986\nindex.android.bundle:2303:194\nc@index.android.bundle:2300:1896\nindex.android.bundle:2300:2523\nindex.android.bundle:2295:2662\nindex.android.bundle:2287:1097\nindex.android.bundle:2281:1093\nindex.android.bundle:2280:271\nindex.android.bundle:2278:1994\nindex.android.bundle:2277:1250\nindex.android.bundle:2267:861\nv@index.android.bundle:2268:3987\nindex.android.bundle:2268:5380\nindex.android.bundle:2265:3110\nindex.android.bundle:2261:1015\nindex.android.bundle:2259:2258\nindex.android.bundle:2234:605\nindex.android.bundle:2220:140\no@index.android.bundle:2218:426\nindex.android.bundle:2218:183\nindex.android.bundle:2214:1052\nindex.android.bundle:2203:3842\nindex.android.bundle:2198:4912\nindex.android.bundle:2195:684\nindex.android.bundle:2188:2092\nindex.android.bundle:2167:808\nindex.android.bundle:823:1910\nindex.android.bundle:2030:1938\np@index.android.bundle:91:588\nindex.android.bundle:91:1893\np@index.android.bundle:91:588\no@index.android.bundle:91:1069\nindex.android.bundle:91:1212\nu@index.android.bundle:85:157\nindex.android.bundle:85:866\nindex.android.bundle:93:1662\nk@index.android.bundle:93:498\nw@index.android.bundle:93:888\ncallReactNativeMicrotasks@index.android.bundle:93:3055\nvalue@index.android.bundle:45:2868\nindex.android.bundle:45:960\nvalue@index.android.bundle:45:2504\nvalue@index.android.bundle:45:919\nvalue@[native code]\nvalue@[native code]"}`

Same for my side, plz check it 
@skrafft
